---
title: "RDT_psychometric"
output: html_document
date: "2024-11-25"
---

```{r, echo=FALSE}
## Install/Call needed libraries
# Function to check, install, and load packages
check_and_load <- function(pkg, comment = NULL) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg, dependencies = TRUE)
    library(pkg, character.only = TRUE)
  }
  if (!is.null(comment)) {
    message(comment) # Print the comment for clarity
  }
}

# Load libraries with their descriptions
check_and_load("tidyverse", "# Data wrangling")
check_and_load("readxl", "# Read excel files")
check_and_load("psych", "# Psych stats (e.g., Descriptive statistics, data analysis and visualization)")
check_and_load("ltm", "# Latent trait modeling for item response data")
check_and_load("lubridate", "# Work with date/time data")
check_and_load("DescTools", "# Descriptive statistics and data analysis")
check_and_load("lavaan", "# Structural equation modeling")
check_and_load("rcompanion", "# Spearman's rho with bootstrapped confidence intervals")
check_and_load("corrplot", "# Visualize correlation matrices")
check_and_load("semPlot", "# Visualize SEMs")
check_and_load("irr", "# Intraclass correlation")
```

### Path to data (update)
```{r data_path}
# Path to data of first SONA sample administration of the RDT
data_path_orig <- "cleanedRDTorig.xlsx"

# Path to data of second SONA sample administration of the RDT
data_path_rep <- "cleanedRDTrep.xlsx"

# Path to Qualtrics administration of RDT in fMRI sample 
data_path_fMRI_qual <- "221118_survey_data.csv"

# Path to first in-scanner administration of the RDT in fMRI sample
data_path_fMRI_1 <- "fMRI_RDT1.xlsx"

# Path of second in-scanner administration of the RDT in fMRI sample
data_path_fMRI_2 <- "fMRI_RDT2.xlsx"

# Path to diagnosis key
data_path_diag <- "diagnosis_key.xlsx"
```


# SONA Data

### Exploratory Factor Analysis
```{r efa}
# https://solomonkurz.netlify.app/post/2021-05-11-yes-you-can-fit-an-exploratory-factor-analysis-with-lavaan/

##################
## Read in data ##
##################
  
RDT1 <- read_excel(data_path_orig) %>%
  dplyr::select(-c(starts_with("Attention"))) %>% # drop those who fail attention questions
  arrange(lubridate::ymd_hms(EndDate)) %>% # order by date 
  mutate(Sample = ifelse(row_number() %in% 1:418, "1", "2")) %>% # all survey from 2021 = sample 1, 2022 = sample 2
  subset(Sample == "1") %>% 
  dplyr::select(RDT_01:RDT_03, RDT_07:RDT_09, RDT_13:RDT_15, RDT_19:RDT_21, RDT_25:RDT_27) %>% 
  drop_na() # No missing responses to individual items, only empty responses

#####################################
## Is factor analysis appropriate? ##
#####################################

# Correlation matrix, original scores
datamatrix <- cor(RDT1, use = "complete.obs")
corrplot(datamatrix, method="number")

## KMO Factorability untransformed
KMO(r=cor(RDT1))

# Bartlett's test of sphericity untransformed
cortest.bartlett(RDT1)

# Positive determinant - factor analysis will probably run
det(cor(RDT1))

#################################
## Determine Number of Factors ##
#################################

## Screeplot
ev <- eigen(cor(RDT1), symmetric = TRUE) # eigenvalues greater than one = 2
ev$values

scree(RDT1) # 1 factor, 2 components

# Create scree plot for manuscript
fafitfree <- fa(RDT1,nfactors = ncol(RDT1), rotate = "none") # 1 factor
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)
ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  theme_bw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
  theme(text = element_text(size=12,  family="Times New Roman")) +
  scale_y_continuous(breaks = c(1, 2, 3, 4, 5, 6, 7), limits = c(0,7)) +
  xlab("Number of Factors") +
  ylab("Eigenvalue") +
  labs( title = "Scree Plot") + 
  geom_hline(yintercept = 1, col = "#FAC898")

## Export scree plot
#ggsave(filename = paste("EFA_scree.png"), width = 6, height = 5,
#       path = "", 
#       units = c("in"), dpi = 300)

## Parallel analysis
fa.parallel(RDT1, fa="fa", n.obs = 392) # 4 factors
fa.parallel(RDT1)

###################
## Define Models ##
###################

# 1-factor model
f1 <- '
efa("efa")*f1 =~ RDT_01 + RDT_02 + RDT_03 + RDT_07 + RDT_08 + RDT_09 + RDT_13 + RDT_14 + RDT_15 +
                 RDT_19 + RDT_20 + RDT_21 + RDT_25 + RDT_26 + RDT_27
'

# 2-factor model
f2 <- '
efa("efa")*f1 +
efa("efa")*f2 =~ RDT_01 + RDT_02 + RDT_03 + RDT_07 + RDT_08 + RDT_09 + RDT_13 + RDT_14 + RDT_15 +
                 RDT_19 + RDT_20 + RDT_21 + RDT_25 + RDT_26 + RDT_27
'

# 4-factor model
f4 <- '
efa("efa")*f1 +
efa("efa")*f2 +
efa("efa")*f3 +
efa("efa")*f4 =~ RDT_01 + RDT_02 + RDT_03 + RDT_07 + RDT_08 + RDT_09 + RDT_13 + RDT_14 + RDT_15 +
                 RDT_19 + RDT_20 + RDT_21 + RDT_25 + RDT_26 + RDT_27
'

#################
## Perform EFA ##
#################

efa_f1 <- 
  cfa(model = f1,
      data = RDT1,
      rotation = "oblimin",
      estimator = "WLSMV",
      ordered = TRUE)

efa_f2 <- 
  cfa(model = f2,
      data = RDT1,
      rotation = "oblimin",
      estimator = "WLSMV",
      ordered = TRUE)

efa_f4 <- 
  cfa(model = f4,
      data = RDT1,
      rotation = "oblimin",
      estimator = "WLSMV",
      ordered = TRUE)

summary(efa_f1, fit.measures = TRUE, standardized = TRUE)
summary(efa_f2, fit.measures = TRUE, standardized = TRUE)
summary(efa_f4, fit.measures = TRUE, standardized = TRUE)

#################
## Compare Fit ##
#################

# define the fit measures
fit_measures_robust <- c("chisq.scaled", "df", "pvalue.scaled", 
                         "cfi.scaled", "rmsea.scaled", "srmr")

# collect them for each model
rbind(fitmeasures(efa_f1, fit_measures_robust),
      fitmeasures(efa_f2, fit_measures_robust),
      fitmeasures(efa_f4, fit_measures_robust)) %>% 
  data.frame() %>% 
  mutate(chisq.scaled  = round(chisq.scaled, digits = 2),
         df            = as.integer(df),
         pvalue.scaled = ifelse(pvalue.scaled == 0, "< .001", pvalue.scaled)) %>% 
  mutate_at(vars(cfi.scaled:srmr), ~round(., digits =  3))
```

### Reliability
```{r reliability1}
################################
## RDT - SONA Sample - Retest ##
################################

# Read in data from original survey 
orig <- read_excel(data_path_orig) %>%
  dplyr::select(EndDate, id, dup, RDT_01:RDT_30, PIOS_01:PIOS_15, SCF_01:SCF_12) %>% 
  dplyr::select(-c(starts_with("Attention"))) %>% # remove attention questions
  arrange(lubridate::ymd_hms(EndDate)) %>% # order by date 
  mutate(Sample = ifelse(row_number() %in% 1:418, "1", "2")) # all survey from 2021 = sample 1, 2022 = sample 2

# Read in data from follow-up survey (used for test-retest purposes)
rep <- read_excel(data_path_rep) %>% 
  dplyr::select(EndDate, id, starts_with("RDT")) %>% 
  slice(-c(1,2)) %>% 
  arrange(lubridate::ymd_hms(EndDate)) %>% # order by date
  mutate(Sample = ifelse(row_number() %in% 1:244, "1", "2")) # all survey from 2021 = sample 1, 2022 = sample 2

####################
## RDT score orig ##
####################

# Total Score
RDT_columns <- c("RDT_01","RDT_02","RDT_03", "RDT_07","RDT_08", "RDT_09","RDT_13","RDT_14",
                 "RDT_15", "RDT_19","RDT_20","RDT_21","RDT_25","RDT_26","RDT_27")
orig[,RDT_columns] <- lapply(orig[,RDT_columns], as.numeric)
orig$RDT_Mean <- rowMeans(orig[,RDT_columns])

# Factor 1
RDT_F1 <- c("RDT_01","RDT_02","RDT_03","RDT_07","RDT_09","RDT_13","RDT_19","RDT_25","RDT_26", "RDT_27")
orig$RDT_f1 <- rowMeans(orig[,RDT_F1])

# Factor 2
RDT_F2 <- c("RDT_08","RDT_14","RDT_15","RDT_20","RDT_21")
orig$RDT_f2 <- rowMeans(orig[,RDT_F2])

####################
## RDT score rep ##
####################

# Total Score
rep[,RDT_columns] <- lapply(rep[,RDT_columns], as.numeric)
rep$RDT_Mean <- rowMeans(rep[,RDT_columns])

# Factor 1
rep$RDT_f1 <- rowMeans(rep[,RDT_F1])

# Factor 2
rep$RDT_f2 <- rowMeans(rep[,RDT_F2])

############################
## Descriptive Statistics ##
############################

# Original administration Factor 1
orig %>% group_by(Sample) %>% 
  dplyr::summarize(mean = mean(RDT_f1, na.rm = TRUE), median = median(RDT_f1, na.rm = TRUE), sd = sd(RDT_f1, na.rm = TRUE), n = n())

# Original administration Factor 2
orig %>% group_by(Sample) %>% 
  summarize(mean = mean(RDT_f2, na.rm = TRUE), median = median(RDT_f2, na.rm = TRUE), sd = sd(RDT_f2, na.rm = TRUE), n = n())

# Test-retest administration Factor 1
rep %>% group_by(Sample) %>% 
  dplyr::summarize(mean = mean(RDT_f1, na.rm = TRUE), median = median(RDT_f1, na.rm = TRUE), sd = sd(RDT_f1, na.rm = TRUE), n = n())

# Test-retest administration Factor 2
rep %>% group_by(Sample) %>% 
  summarize(mean = mean(RDT_f2, na.rm = TRUE), median = median(RDT_f2, na.rm = TRUE), sd = sd(RDT_f2, na.rm = TRUE), n = n())

######################
## Combine datasets ##
######################

## Dropping duplicates also gets rid of the skeleton entries (e.g., blank responses)
# Only need RDT mean totals 
df <- orig %>% 
  subset(dup == 0) %>% 
  dplyr::select(id, dup, Sample, RDT_Mean, RDT_f1, RDT_f2) %>% 
  left_join(rep, by = c("id" = "id", "Sample" = "Sample"))


## separate by sample 
Sample1 <- df %>% 
  subset(Sample == 1) %>% 
  drop_na()

Sample2 <- df %>% 
  subset(Sample == 2) %>% 
  drop_na()

##### ##### ##### ##### 
##### Reliability ##### 
##### ##### ##### ##### 

## Spearman's Rank-Order Correlation for test-retest 
SpearmanRho(Sample1$RDT_f1.x, Sample1$RDT_f1.y, use = c("complete.obs"), conf.level = 0.95)
SpearmanRho(Sample1$RDT_f2.x, Sample1$RDT_f2.y, use = c("complete.obs"), conf.level = 0.95)
SpearmanRho(Sample1$RDT_Mean.x, Sample1$RDT_Mean.y, use = c("complete.obs"), conf.level = 0.95)

SpearmanRho(Sample2$RDT_f1.x, Sample2$RDT_f1.y, use = c("complete.obs"), conf.level = 0.95)
SpearmanRho(Sample2$RDT_f2.x, Sample2$RDT_f2.y, use = c("complete.obs"), conf.level = 0.95)
SpearmanRho(Sample2$RDT_Mean.x, Sample2$RDT_Mean.y, use = c("complete.obs"), conf.level = 0.95)


######################
## Cronbach's alpha ##
######################

## RDT_f1 2021 Sample
rdt_2021_f1 <- orig %>% 
  subset(Sample == 1) %>% 
  dplyr::select(all_of(RDT_F1))

# Compute Cronbach's Alpha 
cronbach.alpha(rdt_2021_f1, na.rm = TRUE, CI = TRUE)

# RDT_f2 2021 Sample
rdt_2021_f2 <- orig %>% 
  subset(Sample == 1) %>% 
  dplyr::select(all_of(RDT_F2))

# Compute Cronbach's Alpha 
cronbach.alpha(rdt_2021_f2, na.rm = TRUE, CI = TRUE)

# RDT_f1 2022 Sample
rdt_2022_f1 <- orig %>% 
  subset(Sample == 2) %>% 
  dplyr::select(all_of(RDT_F1))

# Compute Cronbach's Alpha 
cronbach.alpha(rdt_2022_f1, na.rm = TRUE, CI = TRUE) 

# RDT_f2 2021 Sample
rdt_2022_f2 <- orig %>% 
  subset(Sample == 2) %>% 
  dplyr::select(all_of(RDT_F2))

# Compute Cronbach's Alpha 
cronbach.alpha(rdt_2022_f2, na.rm = TRUE, CI = TRUE)
```

### Validity
```{r validity1}
#############################
## RDT - SONA 2021 Sample  ##
#############################

# Read in data from original survey
RDT1 <- read_excel(data_path_orig) %>%
  dplyr::select(-c(starts_with("Attention"))) %>% # remove attention questions
  arrange(lubridate::ymd_hms(EndDate)) %>% # order by date 
  mutate(Sample = ifelse(row_number() %in% 1:418, "1", "2")) %>% 
  subset(Sample == "1")

sona2021 <- RDT1 %>% 
  dplyr::select(starts_with("RDT"), starts_with("PIOS")) %>% 
  mutate(PIOS_Total = rowSums(across(c("PIOS_01","PIOS_02","PIOS_03","PIOS_04","PIOS_05",
                                       "PIOS_06","PIOS_07","PIOS_08","PIOS_09","PIOS_10",
                                       "PIOS_11","PIOS_12","PIOS_13","PIOS_14","PIOS_15"))), 
         RDT_fact1 = rowSums(across(c("RDT_01","RDT_02","RDT_03","RDT_07","RDT_09","RDT_13",
                                      "RDT_19","RDT_25","RDT_26", "RDT_27"))),
         RDT_fact2 = rowSums(across(c("RDT_08","RDT_14","RDT_15","RDT_20","RDT_21")))) %>% 
  dplyr::select(RDT_fact1, RDT_fact2, PIOS_Total) %>% 
  drop_na()

corr2021 <- corr.test(sona2021, method="spearman")
corr2021$ci

#############################
## RDT - SONA 2022 Sample  ##
#############################

# Read in data from original survey
RDT2 <- read_excel(data_path_orig) %>%
  dplyr::select(-c(starts_with("Attention"))) %>% # remove attention questions
  arrange(lubridate::ymd_hms(EndDate)) %>% # order by date 
  mutate(Sample = ifelse(row_number() %in% 1:418, "1", "2")) %>% 
  subset(Sample == "2")

sona2022 <- RDT2 %>% 
  dplyr::select(starts_with("RDT"), starts_with("PIOS")) %>% 
  mutate(PIOS_Total = rowSums(across(c("PIOS_01","PIOS_02","PIOS_03","PIOS_04","PIOS_05",
                                       "PIOS_06","PIOS_07","PIOS_08","PIOS_09","PIOS_10",
                                       "PIOS_11","PIOS_12","PIOS_13","PIOS_14","PIOS_15"))), 
         RDT_fact1 = rowSums(across(c("RDT_01","RDT_02","RDT_03","RDT_07","RDT_09","RDT_13",
                                      "RDT_19","RDT_25","RDT_26", "RDT_27"))),
         RDT_fact2 = rowSums(across(c("RDT_08","RDT_14","RDT_15","RDT_20","RDT_21")))) %>% 
  dplyr::select(RDT_fact1, RDT_fact2, PIOS_Total) %>% 
  drop_na()

corr2022 <- corr.test(sona2022, method="spearman")
corr2022$ci
```

### CFA Residual Calculations
```{r residual calculations}

# Standardized factor loadings from Mplus 2-factor analysis of SONA dataset
sona_factLoadings <- c(0.679, 0.608, 0.69, 0.78, 0.718, 0.787, 
              0.752, 0.614, 0.534, 0.863, 0.869, 0.685, 
              0.742, 0.881, 0.736)

# Calculate uniqueness (error variances)
(sona_residuals <- 1 - sona_factLoadings^2)

```


# fMRI Data

### Reliability
```{r reliability2}
##################
## Read in data ##
##################

# Qualtrics administration of RDT
qual <- read_csv(data_path_fMRI_qual) %>% 
  filter(SUBJID != "MW28ZD" & SUBJID != "SE17RN" & SUBJID != "LT72ET") %>%  # Three participants didn't take the RDT
  dplyr::select(SUBJID, RDT_1,RDT_2, RDT_3, RDT_7, RDT_8, RDT_9, RDT_13, RDT_14, RDT_15, RDT_19, RDT_20, RDT_21,
                RDT_25, RDT_26, RDT_27)

# In-scanner administration of RDT
fMRI1 <- read_excel(data_path_fMRI_1) %>% 
  dplyr::select(SUBJID, phase3, "RDT_1","RDT_2","RDT_3", "RDT_7","RDT_8", "RDT_9","RDT_13","RDT_14",
                "RDT_15", "RDT_19","RDT_20","RDT_21","RDT_25","RDT_26","RDT_27") 
fMRI2 <- read_excel(data_path_fMRI_2) %>% 
  dplyr::select(SUBJID, phase3, "RDT_1","RDT_2","RDT_3", "RDT_7","RDT_8", "RDT_9","RDT_13","RDT_14",
                "RDT_15", "RDT_19","RDT_20","RDT_21","RDT_25","RDT_26","RDT_27") %>% 
  filter(!SUBJID %in% c("QM43RU", "DF57LF", "EM46EU", "AW84RQ", "GX39NL", "HN40PN", "YK56GZ","YG64UC",
                        "AX44QR", "PU53AJ", "NG55ZP","SU56GA")) # These participants don't have a second in-scanner RDT administration

# Diagnosis key (i.e., control, OCD, or undetermined)
diag <- read_excel(data_path_diag)

#############################
## RDT score Qualrics Data ##
#############################

# Total Score
RDT_columns <- c("RDT_1","RDT_2","RDT_3", "RDT_7","RDT_8", "RDT_9","RDT_13","RDT_14",
                 "RDT_15", "RDT_19","RDT_20","RDT_21","RDT_25","RDT_26","RDT_27")
qual$RDT_Mean_qual <- rowMeans(qual[,RDT_columns])


# Factor 1
RDT_F1 <- c("RDT_1","RDT_2","RDT_3","RDT_7","RDT_9","RDT_13","RDT_19","RDT_25","RDT_26", "RDT_27")
qual$RDT_f1_qual <- rowMeans(qual[,RDT_F1])

# Factor 2
RDT_F2 <- c("RDT_8","RDT_14","RDT_15","RDT_20","RDT_21")
qual$RDT_f2_qual <- rowMeans(qual[,RDT_F2])


##########################
## RDT score in-Scanner ##
##########################

# Total Score
fMRI1$RDT_Mean_fMRI1 <- rowMeans(fMRI1[,RDT_columns])
fMRI2$RDT_Mean_fMRI <- rowMeans(fMRI2[,RDT_columns])

# Factor 1
fMRI1$RDT_f1_fMRI1 <- rowMeans(fMRI1[,RDT_F1])
fMRI2$RDT_f1_fMRI2 <- rowMeans(fMRI2[,RDT_F1])

# Factor 2
fMRI1$RDT_f2_fMRI1 <- rowMeans(fMRI1[,RDT_F2])
fMRI2$RDT_f2_fMRI2 <- rowMeans(fMRI2[,RDT_F2])

######################
## Combine datasets ##
######################

# Only need RDT mean totals 
comb <- qual %>% 
  left_join(fMRI1, by = "SUBJID") %>% 
  left_join(fMRI2, by = c("SUBJID", "phase3")) %>% 
  left_join(diag, by = "SUBJID") %>% 
  dplyr::select(SUBJID, Group, starts_with("RDT_Mean"), starts_with("RDT_f1"), starts_with("RDT_f2"))

############################
## Descriptive Statistics ##
############################

comb %>% group_by(Group) %>% 
  summarise(mean = mean(RDT_f1_qual, na.rm = TRUE), median = median(RDT_f1_qual, na.rm = TRUE), sd(RDT_f1_qual, na.rm = TRUE), n = n())

comb %>% group_by(Group) %>% 
  summarise(mean = mean(RDT_f2_qual, na.rm = TRUE), median = median(RDT_f2_qual, na.rm = TRUE), sd(RDT_f2_qual, na.rm = TRUE), n = n())

##### ##### ##### ##### 
##### Reliability ##### 
##### ##### ##### ##### 

# Figure out N for correlations
count <- comb %>% 
  drop_na(RDT_Mean_qual, RDT_Mean_fMRI1) # 91, 92, 84

## Spearman's Rank-Order Correlation for test-retest 
SpearmanRho(comb$RDT_f1_qual, comb$RDT_f1_fMRI1, use = c("complete.obs"), conf.level = 0.95)
SpearmanRho(comb$RDT_f2_qual, comb$RDT_f2_fMRI1, use = c("complete.obs"), conf.level = 0.95)
SpearmanRho(comb$RDT_Mean_qual, comb$RDT_Mean_fMRI1, use = c("complete.obs"), conf.level = 0.95)

## For agreement across 3 time points
factor1 <- comb %>% 
  dplyr::select(starts_with("RDT_f1")) 

factor2 <- comb %>% 
  dplyr::select(starts_with("RDT_f2")) 

icc(factor1, model = "twoway", type = "agreement", unit = "average", conf.level = 0.95)
icc(factor2, model = "twoway", type = "agreement", unit = "average", conf.level = 0.95)

######################
## Cronbach's alpha ##
######################

## QUALTRICS 

# RDT_f1 qual Sample
qual_f1 <- qual %>% 
  dplyr::select(all_of(RDT_F1))
cronbach.alpha(qual_f1, na.rm = TRUE, CI = TRUE)

# RDT_f2 qual Sample
qual_f2 <- qual %>% 
  dplyr::select(all_of(RDT_F2))
cronbach.alpha(qual_f2, na.rm = TRUE, CI = TRUE)

## in-SCANNER RUN 1

# RDT_f1 
fMRI1_f1 <- fMRI1 %>% 
  dplyr::select(all_of(RDT_F1))
cronbach.alpha(fMRI1_f1, na.rm = TRUE, CI = TRUE)

# RDT_f2 
fMRI1_f2 <- fMRI1 %>% 
  dplyr::select(all_of(RDT_F2))
cronbach.alpha(fMRI1_f2, na.rm = TRUE, CI = TRUE)

## in-SCANNER RUN 2

# RDT_f1 
fMRI2_f1 <- fMRI2 %>% 
  dplyr::select(all_of(RDT_F1))
cronbach.alpha(fMRI2_f1, na.rm = TRUE, CI = TRUE)

# RDT_f2 
fMRI2_f2 <- fMRI2 %>% 
  dplyr::select(all_of(RDT_F2))
cronbach.alpha(fMRI2_f2, na.rm = TRUE, CI = TRUE)
```

### Validity
```{r validity2}
##################
## Read in data ##
##################
FMRI <- read_csv(data_path_fMRI_qual) %>% 
  filter(SUBJID != "MW28ZD" & SUBJID != "SE17RN" & SUBJID != "LT72ET") # They didn't take the phase 2 surveys

# Isolate by group/diagnosis, score RDT and PIOS
fMRI_scrup <- FMRI %>% 
  subset(Group == "Scrupulosity") %>% 
  dplyr::select(starts_with("RDT"), starts_with("PIOS")) %>% 
  mutate(PIOS_Total = rowSums(across(c("PIOS_1","PIOS_2","PIOS_3","PIOS_4","PIOS_5",
                                       "PIOS_6","PIOS_7","PIOS_8","PIOS_9","PIOS_10",
                                       "PIOS_11","PIOS_12","PIOS_13","PIOS_14","PIOS_15"))), 
         RDT_fact1 = rowSums(across(c("RDT_1","RDT_2","RDT_3","RDT_7","RDT_9","RDT_13",
                                      "RDT_19","RDT_25","RDT_26", "RDT_27"))),
         RDT_fact2 = rowSums(across(c("RDT_8","RDT_14","RDT_15","RDT_20","RDT_21")))) %>% 
  dplyr::select(RDT_fact1, RDT_fact2, PIOS_Total) %>% 
  drop_na()

fMRI_cont <- FMRI %>% 
  subset(Group == "Control") %>% 
  dplyr::select(starts_with("RDT"), starts_with("PIOS")) %>% 
  mutate(PIOS_Total = rowSums(across(c("PIOS_1","PIOS_2","PIOS_3","PIOS_4","PIOS_5",
                                       "PIOS_6","PIOS_7","PIOS_8","PIOS_9","PIOS_10",
                                       "PIOS_11","PIOS_12","PIOS_13","PIOS_14","PIOS_15"))), 
         RDT_fact1 = rowSums(across(c("RDT_1","RDT_2","RDT_3","RDT_7","RDT_9","RDT_13",
                                      "RDT_19","RDT_25","RDT_26", "RDT_27"))),
         RDT_fact2 = rowSums(across(c("RDT_8","RDT_14","RDT_15","RDT_20","RDT_21")))) %>% 
  dplyr::select(RDT_fact1, RDT_fact2, PIOS_Total) %>% 
  drop_na()

fMRI_undeter <- FMRI %>% 
  subset(Group == "Undetermined") %>% 
  dplyr::select(starts_with("RDT"), starts_with("PIOS")) %>% 
  mutate(PIOS_Total = rowSums(across(c("PIOS_1","PIOS_2","PIOS_3","PIOS_4","PIOS_5",
                                       "PIOS_6","PIOS_7","PIOS_8","PIOS_9","PIOS_10",
                                       "PIOS_11","PIOS_12","PIOS_13","PIOS_14","PIOS_15"))), 
         RDT_fact1 = rowSums(across(c("RDT_1","RDT_2","RDT_3","RDT_7","RDT_9","RDT_13",
                                      "RDT_19","RDT_25","RDT_26", "RDT_27"))),
         RDT_fact2 = rowSums(across(c("RDT_8","RDT_14","RDT_15","RDT_20","RDT_21")))) %>% 
  dplyr::select(RDT_fact1, RDT_fact2, PIOS_Total) %>% 
  drop_na()

# Spearman's correlations between RDT and PIOS
corrfMRIscrup <- corr.test(fMRI_scrup, method="spearman")
corrfMRIcont <- corr.test(fMRI_cont, method="spearman")
corrfMRIscrup$ci
corrfMRIcont$ci
```

### CFA Residual Calculations
```{r residualCalculations2}

# Standardized factor loadings from Mplus 2-factor analysis of SONA dataset
fMRI_factLoadings <- c(0.832, 0.88, 0.83, 0.813, 0.855, 0.903, 
                       0.851, 0.831, 0.86, 0.916, 0.87, 0.73, 
                       0.775, 0.901, 0.827)

# Calculate uniqueness (error variances)
(fMRI_residuals <- 1 - fMRI_factLoadings^2)

```


### Mann-Whitney U Test
```{r u-test}
##################
## Read in data ##
##################
qual <- read_csv(data_path_fMRI_qual)

# Factor 1
RDT_F1 <- c("RDT_1","RDT_2","RDT_3","RDT_7","RDT_9","RDT_13","RDT_19","RDT_25","RDT_26", "RDT_27")
qual$RDT_f1_qual <- rowMeans(qual[,RDT_F1])

# Factor 2
RDT_F2 <- c("RDT_8","RDT_14","RDT_15","RDT_20","RDT_21")
qual$RDT_f2_qual <- rowMeans(qual[,RDT_F2])

## Separate into control and scrupulous groups
Scrup <- qual %>% 
  subset(Group == "Scrupulosity") %>% 
  dplyr::select(RDT_f1_qual, RDT_f2_qual)

Control <- qual %>% 
  subset(Group == "Control") %>% 
  dplyr::select(RDT_f1_qual, RDT_f2_qual)

#########################
## Mann–Whitney U test ##
#########################
# More appropriate for a nonparametric test of the null hypothesis 
wilcox.test(Scrup$RDT_f1_qual, Control$RDT_f1_qual, exact = FALSE, conf.int = TRUE)
wilcox.test(Scrup$RDT_f2_qual, Control$RDT_f2_qual, exact = FALSE, conf.int = TRUE)
```







